import { Certificate } from './certificate-schema';

const certificates: Certificate[] = [
  {
    id: '2024-gcsj-d80d93c2',
    name: 'Mithilesh Mahajan',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-09f09654',
    name: 'Rutuja Rangrao Bedage',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-72c404ee',
    name: 'Priya Pramod Narsugade',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-ecb46c75',
    name: 'Riya Jadhav',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-9ce229a2',
    name: 'Kaivalya Beohar',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-f9a99708',
    name: 'Sajid Kamal',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-70e82e6c',
    name: 'Sujay Deshpande',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-9aeeefd0',
    name: 'Dhawal Thombare',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-d93555b9',
    name: 'Aditya Shinde',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-4c7f7f55',
    name: 'Shubhangi Ramesh Nimbalkar',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-70079435',
    name: 'Pushkar Sandeep Charkha',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-b7316c6c',
    name: 'Atharva Khadake',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-102e82e2',
    name: 'Vishwanath Mishra',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-102e82e2',
    name: 'Vishwanath Mishra',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-4253804e',
    name: 'Yash Kamlesh Kataria',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-fbf47d83',
    name: 'Jay Ajitkumar Patil',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-0155ba79',
    name: 'Alpesh Vijay Thool',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-d559a775',
    name: 'Tushar Nagnath Jamdade',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-3b824476',
    name: 'Manohar Prashant Sonsale',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-2dca583e',
    name: 'Saqlain Mushtaq Shaikh',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-0f921c25',
    name: 'Shravani Anil Korde',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-b3effe6b',
    name: 'Snehal Sandip Wadhane',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-32481dd8',
    name: 'Devendra Moharir',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-88628b3e',
    name: 'Shlesha Shashikant Patil',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
  {
    id: '2024-gcsj-6e168a3c',
    name: 'Tanishka Manoj Suryvanshi',
    eventName: 'GenAI Cloud Study Jams',
    issueDate: '2024-11-20',
    organizer: 'GDG VIIT',
  },
];

export async function getCertificateDetails(id: string): Promise<Certificate | undefined> {
  // In a real application, this would fetch data from a database or API
  // For now, we'll use some static data

  return certificates.find((certificate) => certificate.id === id);
}
